version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lockena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VeryStrongPassword123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./Lockena.Backend
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=lockena;Username=postgres;Password=VeryStrongPassword123!
      AllowedCorsOrigins: "https://localhost:5173"
      TelegramBotToken: "BotToken" #Токен из @BotFather для работы Telegram Mini App
      LogoDevApiKey: "ApiKey" #API ключ от сервиса logo.dev для загрузки логотипов
      ResendApiKey: "Api Key From resend.dev" #API ключ от сервиса resend.dev для отправки почты
      LinkForEmailConfirmation: "https://localhost:5173/email-confirmation/" #Ссылка для подтверждения почты
      JwtSettings__SecretKey: "VeryVeryVeryStrongJWTKey12345678" #JWT ключ минимум 32 символа
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - postgres
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./lockena-frontend
    restart: unless-stopped
    expose:
      - "80"

  miniapp:
    build:
      context: ./lockena-miniapp
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - miniapp
    restart: unless-stopped

volumes:
  pgdata:
